# Local configuration file - DO NOT MODIFY
# This file is automatically generated by the build process

# API Configuration
api_key = "local-dev-key-123456"
api_endpoint = "https://api.local.dev"

# Database Configuration
db_host = "localhost"
db_port = 5432
db_user = "local_user"
db_password = "local_password"
db_name = "local_app"

# App Configuration
app_secret = "local-secret-key"
debug = True
