# Config package initialization
# This file is automatically generated - DO NOT MODIFY

from .settings import *
from .local_settings import *

# API Configuration
API_KEY = "pkg-api-key-12345"
API_SECRET = "pkg-api-secret-67890"

# Database Configuration
DB_PASSWORD = "pkg-db-password"
DB_SECRET = "pkg-db-secret"

# App Configuration
APP_SECRET = "pkg-app-secret"
SECURE_KEY = "pkg-secure-key"

# Import from root config.py
try:
    from ..config import *
except ImportError:
    pass
